services:
  web:
    image: kalmiya:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/postgres
      - RAILS_SERVE_STATIC_FILES=1
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ./config/master.key:/app/config/master.key
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
