---
name: Rails CI
on: [push]
env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn install
  assets:
    runs-on: ubuntu-latest
    needs:
      - bundle
      - yarn
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .node-version
          cache: yarn
      - uses: actions/cache@v3
        with:
          key: ${{ hashFiles('app/assets/**') }}-${{ hashFiles('app/javascript/**') }}
          path: public/assets
      - run: bin/rails assets:precompile
  reek:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec reek
  rubocop:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop
  rspec:
    runs-on: ubuntu-latest
    needs:
      - assets
    env:
      PGHOST: localhost
      PGUSER: kalmiya
      PGPASSWORD: kalmiya
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: kalmiya_test
          POSTGRES_PASSWORD: kalmiya
          POSTGRES_USER: kalmiya
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/cache@v3
        with:
          key: ${{ hashFiles('app/assets/**') }}-${{ hashFiles('app/javascript/**') }}
          path: public/assets
      - run: bin/rails db:setup
      - run: bin/rails spec
