---
name: Rails CI
on: [push]
env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
  reek:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Reek
        run: bundle exec reek
  rubocop:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
  rspec:
    needs:
      - reek
      - rubocop
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: kalmiya
      PGPASSWORD: kalmiya
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: kalmiya_test
          POSTGRES_PASSWORD: kalmiya
          POSTGRES_USER: kalmiya
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database
        run: bin/rails db:setup
      - name: Run RSpec
        run: bin/rails spec
